### PR TITLE
encapp: Add support for buffer decoder

### PR DESCRIPTION
**Pull request by prtmD**
Contribution from Ittiam Systems Pvt. Ltd.

### CODE REVIEW

**Review by chemag — CHANGES_REQUESTED** [review]
This is wrong: APKs cannot be changed. If you want to add a new build, you need to bump up the version number. Check how this is done in other patches.  

The code change here is a minor comment addition. Please move that to a separate diff

**Comment by prtmD** [comment]
> This is wrong: APKs cannot be changed. If you want to add a new build, you need to bump up the version number. Check how this is done in other patches.
Sure I will update the version number to "1.10". Do let me know if the number is incorrect. 


> The code change here is a minor comment addition. Please move that to a separate diff
My apologies, I did not understand this part. Apart from comment addition, the "YUV_DUMP" flag is disabled, which will not write the output YUV file. 
Should I club together my two commits and raise a new PR?

**Comment by chemag** [comment]
> My apologies, I did not understand this part. Apart from comment addition, the "YUV_DUMP" flag is disabled, which will not write the output YUV file.
> Should I club together my two commits and raise a new PR?

You need to split the second path in 2, for a total of 3 patches. The last one should mimic https://github.com/JohanBlome/encapp/commit/bf86aed13a630ee5f377abcb2212854db7d67d1a

**Comment by chemag** [comment]
> > My apologies, I did not understand this part. Apart from comment addition, the "YUV_DUMP" flag is disabled, which will not write the output YUV file.
> > Should I club together my two commits and raise a new PR?
> 
> You need to split the second path in 2, for a total of 3 patches. The last one should mimic [bf86aed](https://github.com/JohanBlome/encapp/commit/bf86aed13a630ee5f377abcb2212854db7d67d1a)

Or, even better, just remove the apk from the second patch, and change its description (it's not "encapp: add APK with buffer decoder support" anymore). Then let the maintainer cut a new apk

**Pull request merged**
